### ISSUE TITLE
'nlcst-to-string' dependency is missing after npm installation

### ISSUE THREAD

**Issue by skrzyneckik** [facundoolano/google-play-keywords#1]
First of all, my knowledge about node.js and npm is really basic, but I think that npm handles providing missing dependencies of package which I try to install.

Anyway, I installed google-play-keywords using npm and I started node console. When I tried to define constant 'keywords', following error was thrown:

> Error: Cannot find module 'nlcst-to-string'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kskrzynecki/node_modules/google-play-keywords/lib/app.js:5:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kskrzynecki/node_modules/google-play-keywords/index.js:3:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

It was easy to resolve by installing extra dependency, but I just wonder shouldn't be handled by npm in the first place? Maybe google-play-keywords dependencies aren't defined properly?

**Comment by facundoolano** [comment]
You're right, I sort of thought that came together with the `retext` dependency. Fixed and published a new version.

Thanks!
